config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :users , only: [:index]

  resources :perfils do
    member do
      put "like" , to: "perfils#upvote"
    end
    resources :comments , only: [:create , :destroy , :upvote , :downvote] do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  resources :places

  resources :transports do
    member do
      put "like" , to: "transports#upvote"
    end
    resources :comments , only: [:create , :destroy , :upvote , :downvote] do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  resources :ocios do
    member do
      put "like" , to: "ocios#upvote"
    end
    resources :comments , only: [:create , :destroy , :upvote , :downvote]  do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  resources :alojamientos  do
    member do
      put "like" , to: "alojamientos#upvote"
    end
    resources :comments  , only: [:create , :destroy , :upvote , :downvote] do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  root 'places#index'

  get "/term" => "places#term"
  get "/norm" => "places#norm"
  get "/nosotros" => "places#nosotros"
  

end

app/models/alojamiento.rb
class Alojamiento < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_one :pic , as: :imageable , dependent: :destroy
  has_many :comments , as: :commentable , dependent: :destroy
  accepts_nested_attributes_for :pic , allow_destroy: true
  validates_associated :pic

  scope :like, ->(args) { where("LOWER(city) like LOWER('%#{args}%') OR LOWER(cat) like LOWER('%#{args}%') OR LOWER(title) like LOWER('%#{args}%') ")}
  scope :cate, ->(args) { where(" LOWER(cat) = LOWER('#{args}') ")}
  scope :ciudad, ->(args) { where(" LOWER(city) like LOWER('%#{args}%') ")}

end

app/controllers/alojamientos_controller.rb
class AlojamientosController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
  before_action :set_alojamiento , only: [:show,:edit , :update , :destroy , :upvote ]
  before_action :alojamiento_auth , only: [ :edit , :update , :destroy ]
  before_action :authenticate! , except: [:index , :show]

  def index
    if params[:cat].blank?
      alojamientos_scope = Alojamiento.all
    else
      alojamientos_scope = Alojamiento.where(cat: params[:cat])
    end
    alojamientos_scope = alojamientos_scope.like(params[:filter]) if params[:filter]
    alojamientos_scope = alojamientos_scope.cate(params[:category]) if params[:category]
    alojamientos_scope = Alojamiento.all if params[:category].blank?
    alojamientos_scope = alojamientos_scope.ciudad(params[:ciudad]) if params[:ciudad]
    # @alojamientos = smart_listing_create :alojamientos, alojamientos_scope, partial: "alojamientos/list", page_sizes: [5, 7, 13, 26]
    @alojamientos = smart_listing_create :alojamientos, alojamientos_scope, partial: 'alojamientos/list'

  end

  def show
    set_meta_tags title: @alojamiento.title ,
                  site: '¡No Canceles!' ,
                  reverse: true ,
                  description: @alojamiento.desc ,
                  keywords: @alojamiento.title.split(" ") << @alojamiento.cat << "alojamiento" << @alojamiento.city ,
                  twitter: {
                    card: "summary",
                    site: "@NoCanceles",
                    title: @alojamiento.title,
                    description: @alojamiento.desc,
                    image: @alojamiento.pic.image.url
                  },
                  og: {
                    title: @alojamiento.title,
                    description:  @alojamiento.desc,
                    type: "website",
                    url: alojamiento_url(@alojamiento),
                    image: @alojamiento.pic.image.url
                  }

  end

  def new
    @alojamiento = current_user.alojamientos.build
    @pic = @alojamiento.build_pic
  end

  def create
    @alojamiento = current_user.alojamientos.build(alojamiento_params)
    if @alojamiento.save
      redirect_to @alojamiento , notice: "Alojamiento creado "
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @alojamiento.update(alojamiento_params)
      redirect_to @alojamiento , notice: "Alojamiento actualizado "
    else
      render 'edit'
    end
  end

  def destroy
    @alojamiento.destroy
    redirect_to root_path , notice: "Alojamiento elimindo"
  end

  def upvote
    @alojamiento.upvote_by current_user
    respond_to do |format|
      format.html {redirect_to :back}
      format.js {render 'alojamientos/vote.js.erb'}
    end
  end

  private

  def set_alojamiento
    @alojamiento = Alojamiento.find(params[:id])
  end

  def alojamiento_auth
    if @alojamiento.user != current_user
      redirect_to @alojamiento , alert: "No autorizado "
    end
  end

  def alojamiento_params
    params.require(:alojamiento).permit(:cat , :title , :dir , :desc , :price , :fecha_ir , :fecha_volver , :city , :unidad ,  pic_attributes: [:id , :image , :_destroy])
  end
end

app/helpers/alojamientos_helper.rb
module AlojamientosHelper
end

app/views/alojamientos/_form.html.haml
= simple_form_for @alojamiento , html: {multipart: true} do |f|
  - if @alojamiento.errors.any?
    #errors
      %h2
      = pluralize(@alojamiento.errors.count , "error")
      prevented this accion from saving
      %ul
        - @alojamiento.errors.full_messages.each  do |msg|
          %li= msg

  .form-group
    = f.simple_fields_for :pic , @pic do |pi|
      = pi.input :image , as: :file , input_html: {class: "form-control"} , label: "Imagen" , hint: "selecciona una imagen de tu reserva" , required: true
  .form-group
    = f.input :cat , collection: ["Hotel","Hostal","Apartahotel","Apartamento"] , input_html: {class: "form-control"} , label: "Tipo De Alojamiento" , hint: "Elige la categoria adecuada", required: true
  .form-group
    = f.input :title , input_html: {class: "form-control"}, placeholder: "Escribe un título" , label: "Título", required: true
  .form-group
    = f.input :desc , input_html: {class: "form-control"} , label: "Descripción" , placeholder: "Indíca si hay condiciones especiales", required: true
  .form-group
    = f.input :city , input_html: {class: "form-control geo"}, placeholder: "Indica la ciudad donde es el alojamiento" , label: "Ciudad", required: true
  .form-group
    = f.input :dir , input_html: {class: "form-control"} , label: "Dirección" , placeholder: "Escribe la dirección correcta ", required: true
  .form-group
    = f.input :fecha_ir , input_html: {class: "form-control"} , label: "Fecha y Hora De Ida", required: true
  .form-group
    = f.input :fecha_volver , input_html: {class: "form-control"} , label: "Fecha y Hora de Vuelta", required: true
  .form-group
    = f.input :price , input_html: {class: "form-control"} , label: "Precio" , placeholder: "Debe ser inferior o igual al precio original", required: true
  .form-group
    = f.input :unidad , collection: ["EURO" , "DÓLAR AMERICANO" , "LIBRA ESTERLINA", "PESO ARGENTINO", "PESO BOLIVIANO","PESO CHILENO","PESO COLOMBIANO" , "PESO MEXICANO"] , input_html: {class: "form-control"} , label: "Unidad De Dinero"  , required: true

  = f.button :submit ,"Crear", class: "btn btn-primary"

app/views/alojamientos/_like.html.haml
= link_to like_alojamiento_path(@alojamiento) , method: :put , remote: true , class: "btn btn-info like " do
  %span.glyphicon.glyphicon-heart
    = @alojamiento.get_upvotes.size
-if user_signed_in? && current_user.id == @alojamiento.user_id
  = link_to  edit_alojamiento_path(@alojamiento) , class: 'btn btn-warning' do
    %span.glyphicon.glyphicon-pencil
  = link_to  @alojamiento , method: :delete , data: {confirm: "Are you sure?"}, class: 'btn btn-danger' do
    %span.glyphicon.glyphicon-trash

app/views/alojamientos/_list.html.haml
- unless smart_listing.empty?
  .table-responsive
    %table.table.table-striped
      %thead
        %th.col-md-2= smart_listing.sortable "Título", "title"
        %th.col-md-2= smart_listing.sortable "Categoria", "cat"
        %th.col-md-1= smart_listing.sortable "Precio", "price"
        %th.col-md-1= smart_listing.sortable "Unidad", "unidad"
        %th.col-md-2= smart_listing.sortable "Ciudad", "city"
        %th.col-md-2= smart_listing.sortable "Fecha-ida", "fecha_ir"
        %th.col-md-2= smart_listing.sortable "Fecha-vuelta", "fecha_volver"

      %tbody
        - smart_listing.collection.each do |alojamiento|
          %tr
            -# User row goes here...
            %td
              = link_to   alojamiento do
                = truncate(alojamiento.title, length: 25)
                %span.badge= alojamiento.comments.count
            %td= alojamiento.cat
            %td= alojamiento.price
            %td= alojamiento.unidad
            %td= alojamiento.city
            %td= alojamiento.fecha_ir.strftime('%d %b %Y %l:%M %p')
            %td= alojamiento.fecha_volver.strftime('%d %b %Y %l:%M %p')


  -# Render nice pagination links fitted for Bootstrap 3 by default
  = smart_listing.paginate
  = smart_listing.pagination_per_page_links
- else
  %p.warning Ningún alojamiento!

app/views/alojamientos/edit.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Editar Alojamiento
      .panel-body
        = image_tag @alojamiento.pic.image.url(:medium)
        = simple_form_for @alojamiento , html: {multipart: true} do |f|
          - if @alojamiento.errors.any?
            #errors
              %h2
              = pluralize(@alojamiento.errors.count , "error")
              prevented this accion from saving
              %ul
                - @alojamiento.errors.full_messages.each  do |msg|
                  %li= msg

          .form-group
            = f.simple_fields_for :pic , @pic do |pi|
              = pi.input :image , as: :file , input_html: {class: "form-control"} , label: "Imagen" , hint: "selecciona una imagen de tu reserva"
          .form-group
            = f.input :cat , collection: ["Hotel","Hostal","Apartahotel","Apartamento"] , input_html: {class: "form-control"} , label: "Tipo De Alojamiento" , hint: "Elige la categoria adecuada", required: true
          .form-group
            = f.input :title , input_html: {class: "form-control"}, placeholder: "Escribe un título" , label: "Título", required: true
          .form-group
            = f.input :desc , input_html: {class: "form-control"} , label: "Descripción" , placeholder: "Indíca si hay condiciones especiales", required: true
          .form-group
            = f.input :city , input_html: {class: "form-control geo"}, placeholder: "Indica la ciudad donde es el alojamiento" , label: "Ciudad", required: true
          .form-group
            = f.input :dir , input_html: {class: "form-control"} , label: "Dirección" , placeholder: "Escribe la dirección correcta ", required: true
          .form-group
            = f.input :fecha_ir , input_html: {class: "form-control"} , label: "Fecha y Hora De Ida", required: true
          .form-group
            = f.input :fecha_volver , input_html: {class: "form-control"} , label: "Fecha y Hora de Vuelta", required: true
          .form-group
            = f.input :price , input_html: {class: "form-control"} , label: "Precio" , placeholder: "Debe ser inferior o igual al precio original", required: true
          .form-group
            = f.input :unidad , collection: ["EURO" , "DÓLAR AMERICANO" , "LIBRA ESTERLINA", "PESO ARGENTINO", "PESO BOLIVIANO","PESO CHILENO","PESO COLOMBIANO" , "PESO MEXICANO"] , input_html: {class: "form-control"} , label: "Unidad De Dinero"  , required: true

          = f.button :submit ,"Actualizar",  class: "btn btn-primary"

app/views/alojamientos/index.html.haml
%h1 Alojamientos
= smart_listing_controls_for(:alojamientos, {class: "form-inline text-right"}) do
  .form-group.filter.input-append
    = text_field_tag :filter, '', class: "search form-control",
                          placeholder: "buscar...", autocomplete: :off
    = select_tag :category, "<option>Hotel</option><option>Hostal</option><option>Apartamento</option><option>Apartahotel</option>".html_safe ,
                          :prompt=>"Todos" ,
                          class: "search form-control",
                          autocomplete: :off
    = text_field_tag :ciudad, '', class: "search form-control ",
                          placeholder: "ciudad...", autocomplete: :off

= smart_listing_render :alojamientos

app/views/alojamientos/index.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :alojamientos %>

app/views/alojamientos/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Crear Alojamiento 
      .panel-body
        = render 'form'

app/views/alojamientos/show.html.haml
.row#pin_show
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.pin_image
        = image_tag @alojamiento.pic.image.url , class: "img-rounded"
      .panel-body
        %h1= @alojamiento.title
        %p
          %h3
            %strong= @alojamiento.cat
          .description= @alojamiento.desc
          El
          %strong precio
          es
          %strong= @alojamiento.price
          %i= @alojamiento.unidad
          y estará en
          %strong= @alojamiento.city
          en
          %strong= @alojamiento.dir
          y la fecha de ida es
          %strong= @alojamiento.fecha_ir.strftime('%d %b %Y %l:%M %p')
          y la vuelta es en
          %strong= @alojamiento.fecha_volver.strftime('%d %b %Y %l:%M %p')
      .panel-footer
        .row
          .col-md-6
            %p.user
              por
              - if @alojamiento.user.perfil.blank?
                %strong= @alojamiento.user.email
              - else
                %strong= link_to @alojamiento.user.email , @alojamiento.user.perfil
          .col-md-6
            %div{class: "btn-group pull-right alojamiento_#{@alojamiento.id}"}
              = render 'alojamientos/like', alojamiento: @alojamiento

%div{class: "comment_alojamiento_#{@alojamiento.id}"}
  = render partial: 'comments/comments' , locals: { commentable: @alojamiento }
%div{class: "form_alojamiento_#{@alojamiento.id}"}
  = render partial: 'comments/form' , locals: { commentable: @alojamiento }

app/views/alojamientos/vote.js.erb
$(".alojamiento_<%= @alojamiento.id %>").html("<%= j (render  partial: 'alojamientos/like' , locals: {alojamiento: @alojamiento }) %>");