config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :users , only: [:index]

  resources :perfils do
    member do
      put "like" , to: "perfils#upvote"
    end
    resources :comments , only: [:create , :destroy , :upvote , :downvote] do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  resources :places

  resources :transports do
    member do
      put "like" , to: "transports#upvote"
    end
    resources :comments , only: [:create , :destroy , :upvote , :downvote] do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  resources :ocios do
    member do
      put "like" , to: "ocios#upvote"
    end
    resources :comments , only: [:create , :destroy , :upvote , :downvote]  do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  resources :alojamientos  do
    member do
      put "like" , to: "alojamientos#upvote"
    end
    resources :comments  , only: [:create , :destroy , :upvote , :downvote] do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  root 'places#index'

  get "/term" => "places#term"
  get "/norm" => "places#norm"
  get "/nosotros" => "places#nosotros"
  

end

app/models/transport.rb
class Transport < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_one :pic , as: :imageable , dependent: :destroy
  has_many :comments , as: :commentable , dependent: :destroy
  accepts_nested_attributes_for :pic , allow_destroy: true
  validates_associated :pic

  scope :like, ->(args) { where("LOWER(to_city) like LOWER('%#{args}%') OR LOWER(from_city) like LOWER('%#{args}%') OR LOWER(cat) like LOWER('%#{args}%') OR LOWER(title) like LOWER('%#{args}%') ")}
  scope :cate, ->(args) { where("LOWER(cat) like LOWER('%#{args}%') ")}
  scope :fciudad, ->(args) { where("LOWER(from_city) like LOWER('%#{args}%') ")}
  scope :tciudad, ->(args) { where("LOWER(to_city) like LOWER('%#{args}%') ")}
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
  before_action :set_transport , only: [:show , :edit , :update , :destroy , :upvote]
  before_action :authenticate! , except: [:index , :show]
  before_action :transport_auth , only: [:edit , :update , :destroy]

  def index
    if params[:cat].blank?
      transports_scope = Transport.all
    else
      transports_scope = Transport.where(cat: params[:cat])
    end
    transports_scope = transports_scope.like(params[:filter]) if params[:filter]
    transports_scope = transports_scope.cate(params[:category]) if params[:category]
    transports_scope = transports_scope.fciudad(params[:fciudad]) if params[:fciudad]
    transports_scope = transports_scope.tciudad(params[:tciudad]) if params[:tciudad]
    # @transports = smart_listing_create :transports, transports_scope, partial: "transports/list", page_sizes: [5, 7, 13, 26]
    @transports = smart_listing_create :transports, transports_scope, partial: 'transports/list'
  end

  def show
    set_meta_tags title: @transport.title ,
                  site: '¡No Canceles!' ,
                  reverse: true ,
                  description: @transport.desc ,
                  keywords: @transport.title.split(" ") << @transport.cat << "transport" << @transport.from_city << @transport.to_city ,
                  twitter: {
                    card: "summary",
                    site: "@NoCanceles",
                    title: @transport.title,
                    description: @transport.desc,
                    image: @transport.pic.image.url
                  },
                  og: {
                    title: @transport.title,
                    description:  @transport.desc,
                    type: "website",
                    url: transport_url(@transport),
                    image: @transport.pic.image.url
                  }
  end

  def new
    @transport = current_user.transports.build
    @pic = @transport.build_pic
  end

  def create
    @transport = current_user.transports.build(transport_params)
    if @transport.save
      redirect_to @transport , notice: "Transporte creado"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @transport.update(transport_params)
      redirect_to @transport , notice: "Transporte actualizado"
    else
      render 'edit'
    end
  end

  def destroy
    @transport.destroy
    redirect_to root_path , notice: "Transporte eliminado"
  end

  def upvote
    @transport.upvote_by current_user
    respond_to do |format|
      format.html {redirect_to :back}
      format.js   {render 'transports/vote.js.erb'}
    end
  end

  private

  def set_transport
    @transport = Transport.find(params[:id])
  end

  def transport_params
    params.require(:transport).permit(:cat , :title , :desc , :from_city , :to_city , :price , :fecha , :unidad , pic_attributes: [:id , :image , :_destroy])
  end

  def transport_auth
    if @transport.user != current_user
      redirect_to @transport , alert: "No autorizado"
    end
  end
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/views/transports/_form.html.haml
= simple_form_for @transport  , html: {multipart: true} do |f|
  - if @transport.errors.any?
    #errors
      %h2
      = pluralize(@transport.errors.count , "error")
      prevented this accion from saving
      %ul
        - @transport.errors.full_messages.each  do |msg|
          %li= msg


  .form-group
    = f.simple_fields_for :pic , @pic do |pi|
      = pi.input :image , as: :file , input_html: {class: "form-control"} , label: "Imagen" , hint: "Seleciona la imagen de tu billete" , required: true
  .form-group
    = f.input :cat , collection: ["Avión" , "Bus" , "Tren"] , input_html: {class: "form-control"} , label: "Billete De" , hint: "Elige la categoria del viaje" , required: true
  .form-group
    = f.input :title , input_html: {class: "form-control"}, placeholder: "Escribe un título" , label: "Título" , required: true
  .form-group
    = f.input :desc , input_html: {class: "form-control"} , label: "Descripción" , placeholder: "Explica las condiciones de tu oferta " , required: true
  .form-group
    = f.input :from_city , input_html: {class: "form-control geo" } , label: "Origen" , placeholder: "Indica la ciudad de salida", required: true
  .form-group
    = f.input :to_city , input_html: {class: "form-control geo"} , label: "Destino" , placeholder: "Indica la ciudad  de llegada", required: true
  .form-group
    = f.input :fecha , input_html: {class: "form-control" } , label: "Fecha y Hora" , hint: "Indica la fecha y la hora de salida", required: true
  .form-group
    = f.input :price , input_html: {class: "form-control"} , label: "Precio" , placeholder: "Debe ser igual o inferior al precio real del billete", required: true
  .form-group
    = f.input :unidad , collection: ["EURO" , "DÓLAR AMERICANO" , "LIBRA ESTERLINA", "PESO ARGENTINO", "PESO BOLIVIANO","PESO CHILENO","PESO COLOMBIANO" , "PESO MEXICANO"] , input_html: {class: "form-control"} , label: "Unidad De Dinero"  , required: true


  = f.button :submit ,"Crear" , class: "btn btn-primary"

app/views/transports/_like.html.haml
= link_to like_transport_path(@transport) , method: :put , remote: true , class: "btn btn-info like" do
  %span.glyphicon.glyphicon-heart
    = @transport.get_upvotes.size
-if user_signed_in? && current_user.id == @transport.user_id
  = link_to  edit_transport_path(@transport) , class: 'btn btn-warning' do
    %span.glyphicon.glyphicon-pencil
  = link_to  @transport , method: :delete , data: {confirm: "Are you sure?"}, class: 'btn btn-danger' do
    %span.glyphicon.glyphicon-trash

app/views/transports/_list.html.haml
- unless smart_listing.empty?
  .table-responsive
    %table.table.table-striped
      %thead
        %th.col-md-2= smart_listing.sortable "Título", :title
        %th.col-md-2= smart_listing.sortable "Categoria", :cat
        %th.col-md-1= smart_listing.sortable "Precio", :price
        %th.col-md-1= smart_listing.sortable "Unidad", :unidad
        %th.col-md-2= smart_listing.sortable "Origen", :from_city
        %th.col-md-2= smart_listing.sortable "Destino", :to_city
        %th.col-md-2= smart_listing.sortable "Fecha", :fecha

      %tbody
        - smart_listing.collection.each do |transport|
          %tr
            -# User row goes here...
            %td
              = link_to transport  do
                = truncate(transport.title, length: 20)
                %span.badge= transport.comments.count
            %td= transport.cat
            %td= transport.price
            %td= transport.unidad
            %td= transport.from_city
            %td= transport.to_city
            %td= transport.fecha.strftime('%d %b %Y %l:%M %p')


  -# Render nice pagination links fitted for Bootstrap 3 by default
  = smart_listing.paginate
  = smart_listing.pagination_per_page_links
- else
  %p.warning Ningún Transporte!

app/views/transports/edit.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Editar Transporte
      .panel-body
        = image_tag @transport.pic.image.url(:medium)
        = simple_form_for @transport  , html: {multipart: true} do |f|
          - if @transport.errors.any?
            #errors
              %h2
              = pluralize(@transport.errors.count , "error")
              prevented this accion from saving
              %ul
                - @transport.errors.full_messages.each  do |msg|
                  %li= msg


          .form-group
            = f.simple_fields_for :pic , @pic do |pi|
              = pi.input :image , as: :file , input_html: {class: "form-control"} , label: "Imagen" , hint: "Seleciona la imagen de tu billete"
          .form-group
            = f.input :cat , collection: ["Avión" , "Bus" , "Tren"] , input_html: {class: "form-control"} , label: "Billete De" , hint: "Elige la categoria del viaje" , required: true
          .form-group
            = f.input :title , input_html: {class: "form-control"}, placeholder: "Escribe un título" , label: "Título" , required: true
          .form-group
            = f.input :desc , input_html: {class: "form-control"} , label: "Descripción" , placeholder: "Explica las condiciones de tu oferta " , required: true
          .form-group
            = f.input :from_city , input_html: {class: "form-control geo" } , label: "Origen" , placeholder: "Indica la ciudad de salida", required: true
          .form-group
            = f.input :to_city , input_html: {class: "form-control geo"} , label: "Destino" , placeholder: "Indica la ciudad  de llegada", required: true
          .form-group
            = f.input :fecha , input_html: {class: "form-control"} , label: "Fecha y Hora" , hint: "Indica la fecha y la hora de salida", required: true
          .form-group
            = f.input :price , input_html: {class: "form-control"} , label: "Precio" , placeholder: "Debe ser igual o inferior al precio real del billete", required: true
          .form-group
            = f.input :unidad , collection: ["EURO" , "DÓLAR AMERICANO" , "LIBRA ESTERLINA", "PESO ARGENTINO", "PESO BOLIVIANO","PESO CHILENO","PESO COLOMBIANO" , "PESO MEXICANO"] , input_html: {class: "form-control"} , label: "Unidad De Dinero"  , required: true


          = f.button :submit ,"Actualizar", class: "btn btn-primary"

app/views/transports/index.html.haml
%h1 Transportes
= smart_listing_controls_for(:transports, {class: "form-inline text-right"}) do
  .form-group.filter.input-append
    = text_field_tag :filter, '', class: "search form-control",
                          placeholder: "buscar...", autocomplete: :off
    = select_tag :category, "<option>Avión</option><option>Bus</option><option>Tren</option>".html_safe ,
                          :prompt=>"Todos" ,
                          class: "search form-control",
                          autocomplete: :off
    = text_field_tag :fciudad, '', class: "search form-control ",
                          placeholder: "origen...", autocomplete: :off
    = text_field_tag :tciudad, '', class: "search form-control ",
                          placeholder: "destino...", autocomplete: :off
= smart_listing_render :transports

app/views/transports/index.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :transports %>

app/views/transports/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Crear Transporte 
      .panel-body
        = render 'form'

app/views/transports/show.html.haml
.row#pin_show
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.pin_image
        = image_tag @transport.pic.image.url , class: "img-rounded"
      .panel-body
        %h1= @transport.title
        %p
          %h3
            %strong= @transport.cat
          .description= @transport.desc
          %strong= @transport.price
          %i= @transport.unidad
          desde
          %strong= @transport.from_city
          a
          %strong= @transport.to_city
          en fecha:
          %strong= @transport.fecha.strftime('%d %b %Y %l:%M %p')
      .panel-footer
        .row
          .col-md-6
            %p.user
              por
              - if @transport.user.perfil.blank?
                %strong= @transport.user.email
              - else
                %strong= link_to @transport.user.email , @transport.user.perfil
          .col-md-6
            %div{class: "btn-group pull-right transport_#{@transport.id}"}
              = render 'transports/like', transport: @transport


%div{class: "comment_transport_#{@transport.id}"}
  = render partial: 'comments/comments' , locals: { commentable: @transport }
%div{class: "form_transport_#{@transport.id}"}
  = render partial: 'comments/form' , locals: { commentable: @transport }

app/views/transports/vote.js.erb
$(".transport_<%= @transport.id %>").html("<%= j (render  partial: 'transports/like' , locals: {transport: @transport }) %>");