config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :users , only: [:index]

  resources :perfils do
    member do
      put "like" , to: "perfils#upvote"
    end
    resources :comments , only: [:create , :destroy , :upvote , :downvote] do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  resources :places

  resources :transports do
    member do
      put "like" , to: "transports#upvote"
    end
    resources :comments , only: [:create , :destroy , :upvote , :downvote] do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  resources :ocios do
    member do
      put "like" , to: "ocios#upvote"
    end
    resources :comments , only: [:create , :destroy , :upvote , :downvote]  do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  resources :alojamientos  do
    member do
      put "like" , to: "alojamientos#upvote"
    end
    resources :comments  , only: [:create , :destroy , :upvote , :downvote] do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  root 'places#index'

  get "/term" => "places#term"
  get "/norm" => "places#norm"
  get "/nosotros" => "places#nosotros"
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :commentable , polymorphic: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate!
  before_action :set_commentable


  def create
     @comment = @commentable.comments.build(comment_params)
     @comment.user_id = current_user.id
     if @comment.save
       respond_to do |format|
         format.html { redirect_to @commentable }
         format.js {render 'comments/create.js.erb'}
       end
     end
  end

  def destroy
    comment = @commentable.comments.find(params[:id])
    comment.destroy
    respond_to do |format|
      format.html { redirect_to @commentable }
      format.js {render 'comments/create.js.erb'}
    end
  end

  def upvote
    @comment = @commentable.comments.find(params[:id])
    @comment.upvote_by current_user
    respond_to do |format|
      format.html {redirect_to :back}
      format.js   { render "comments/vote.js.erb" }
    end
  end

  def downvote
    @comment = @commentable.comments.find(params[:id])
    @comment.downvote_by current_user
    respond_to do |format|
      format.html {redirect_to :back}
      format.js   { render "comments/vote.js.erb" }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_commentable
    if params[:ocio_id]
        @commentable = Ocio.find(params[:ocio_id])
    elsif params[:alojamiento_id]
        @commentable = Alojamiento.find(params[:alojamiento_id])
    elsif params[:transport_id]
        @commentable = Transport.find(params[:transport_id])
    elsif params[:perfil_id]
        @commentable = Perfil.find(params[:perfil_id])
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_likes.html.haml
- if comment.commentable_type == "Ocio"
  = link_to like_ocio_comment_path(commentable , comment) , method: :put  , remote: true ,class: "btn btn-success like-comment" do
    %span.glyphicon.glyphicon-thumbs-up
      = comment.get_upvotes.size
  = link_to dislike_ocio_comment_path(commentable , comment) , method: :put , remote: true  ,class: "btn btn-warning dislike-comment" do
    %span.glyphicon.glyphicon-thumbs-down
      = comment.get_downvotes.size
- elsif comment.commentable_type == "Alojamiento"
  = link_to like_alojamiento_comment_path(commentable , comment) , method: :put , remote:true   , class: "btn btn-success like-comment " do
    %span.glyphicon.glyphicon-thumbs-up
      = comment.get_upvotes.size
  = link_to dislike_alojamiento_comment_path(commentable , comment) , method: :put , remote:true  , class: "btn btn-warning dislike-comment " do
    %span.glyphicon.glyphicon-thumbs-down
      = comment.get_downvotes.size
- elsif comment.commentable_type == "Transport"
  = link_to like_transport_comment_path(commentable , comment) , method: :put , remote:true ,class: "btn btn-success like-comment" do
    %span.glyphicon.glyphicon-thumbs-up
      = comment.get_upvotes.size
  = link_to dislike_transport_comment_path(commentable , comment) , method: :put , remote:true , class: "btn btn-warning dislike-comment" do
    %span.glyphicon.glyphicon-thumbs-down
      = comment.get_downvotes.size
- elsif comment.commentable_type == "Perfil"
  = link_to like_perfil_comment_path(commentable , comment) , method: :put  , remote:true  , class: "btn btn-success like-comment " do
    %span.glyphicon.glyphicon-thumbs-up
      = comment.get_upvotes.size
  = link_to dislike_perfil_comment_path(commentable , comment) , method: :put  , remote:true , class: "btn btn-warning dislike-comment " do
    %span.glyphicon.glyphicon-thumbs-down
      = comment.get_downvotes.size
- if user_signed_in? && current_user.id == comment.user_id
  = link_to  [commentable , comment] , method: :delete , data: {confirm: "seguro?"} , remote: true , class: 'btn btn-danger' do
    %span.glyphicon.glyphicon-trash

app/views/comments/_comments.html.haml
.row
  .col-md-8.col-md-offset-2
    %h3
      %strong= pluralize( commentable.comments.count , "comentario")
    - commentable.comments.each do |comment|
      .panel.panel-info
        .panel-heading.pan-comment
          .row
            .col-md-6
              .commenter
                %strong= comment.user.email
                = time_ago_in_words(comment.created_at )
            .col-md-6
              %div{class: "btn-group pull-right comment_#{comment.id}"}
                = render partial: 'comments/comment_likes' , locals: {comment: comment , commentable: commentable}
        .panel-body.pan
          = comment.body

app/views/comments/_form.html.haml
.row
  .col-md-8.col-md-offset-2
    = simple_form_for [commentable , Comment.new] , html: { id: 'comment_form' } , remote: true do |f|
      .form-group
        = f.input :body , input_html: { class: "form-control"} , placeholder: "Añadir un comentario" , label: false , required: true

      = f.button :submit , "Enviar" , class: "btn btn-primary btn-block"

app/views/comments/create.js.erb
$(".comment_<%= @commentable.class.name.downcase %>_<%= @commentable.id %>").html("<%= j (render  partial: 'comments/comments' , locals: { commentable: @commentable}) %>");
$('#comment_form')[0].reset();
$(".form_<%= @commentable.class.name.downcase %>_<%= @commentable.id %>").html("<%= j (render  partial: 'comments/form' , locals: { commentable: @commentable}) %>");

app/views/comments/vote.js.erb
$(".comment_<%= @comment.id %>").html("<%= j (render  partial: 'comments/comment_likes' , locals: {comment: @comment , commentable: @commentable}) %>");