config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :users , only: [:index]

  resources :perfils do
    member do
      put "like" , to: "perfils#upvote"
    end
    resources :comments , only: [:create , :destroy , :upvote , :downvote] do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  resources :places

  resources :transports do
    member do
      put "like" , to: "transports#upvote"
    end
    resources :comments , only: [:create , :destroy , :upvote , :downvote] do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  resources :ocios do
    member do
      put "like" , to: "ocios#upvote"
    end
    resources :comments , only: [:create , :destroy , :upvote , :downvote]  do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  resources :alojamientos  do
    member do
      put "like" , to: "alojamientos#upvote"
    end
    resources :comments  , only: [:create , :destroy , :upvote , :downvote] do
      member do
        put "like"    , to: "comments#upvote"
        put "dislike" , to: "comments#downvote"
      end
    end
  end

  root 'places#index'

  get "/term" => "places#term"
  get "/norm" => "places#norm"
  get "/nosotros" => "places#nosotros"
  

end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-main-collapse
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed#datebox{"aria-expanded" => "false","data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "No Canceles!" , root_path
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown" , :role => "button"}
            Ofertas
            %span.caret
          %ul.dropdown-menu#demolist
            %li
              = link_to "Transportes" , transports_path
              %span.sr-only (current)
            %li= link_to "Ocios" , ocios_path
            %li= link_to "Alojamientos" , alojamientos_path
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown" , :role => "button"}
            Redes Sociales y Foro
            %span.caret
          %ul.dropdown-menu#demolist
            %li
              .fb-like{"data-action" => "like", "data-href" => "https://www.facebook.com/Nocanceles/", "data-layout" => "button_count", "data-share" => "false", "data-show-faces" => "true"}
            %li
              %a.twitter-follow-button{"data-show-count" => "true", "data-show-screen-name" => "false", :href => "https://twitter.com/nocanceles"} siguenos en @nocanceles
            %li.divider{:role => "separator"}
            %li= link_to "Nuestro Foro", "http://nocanceles.foroactivo.com"

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Nosotros" , "/nosotros"
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown" , :role => "button"}
              Crear Anuncio
              %span.caret
            %ul.dropdown-menu#demolist
              %li= link_to "Nuevo Transporte" , new_transport_path
              %li= link_to "Nuevo Ocio" , new_ocio_path
              %li= link_to "Nuevo Alojamiento" , new_alojamiento_path
              %li.divider{:role => "separator"}
              %li= link_to "Términos de Uso" , "/term"
              %li.divider{:role => "separator"}
              %li= link_to "Normas de Uso" , "/norm"

          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              %span.glyphicon.glyphicon-user
              = current_user.email
              %span.caret
            %ul.dropdown-menu
              - if current_user.perfil.blank?
                %li
                  = link_to  new_perfil_path do
                    %span.glyphicon.glyphicon-user
                    Crear Perfil
              - else
                %li
                  = link_to  current_user.perfil do
                    %span.glyphicon.glyphicon-user
                    Ver Perfil


              %li.divider{:role => "separator"}
              %li
                = link_to  edit_user_registration_path do
                  %span.glyphicon.glyphicon-pencil
                  Editar Cuenta

              %li.divider{:role => "separator"}
              %li
                = link_to  destroy_user_session_path , method: :delete do
                  %span.glyphicon.glyphicon-log-in
                  Salir

              %li.divider{:role => "separator"}
              %li
                = link_to  users_path do
                  %span.glyphicon.glyphicon-user
                  %span.glyphicon.glyphicon-user
                  Usuarios

              - if current_user.try(:admin?)
                %li.divider{:role => "separator"}
                %li
                  = link_to  "/admin" do
                    %span.glyphicon.glyphicon-eye-open
                    Admin
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Nosotros" , "/nosotros"
          %li= link_to "Entrar" , new_user_session_path
          %li= link_to "Registrar" , new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
%html
%head
  
  %meta{:content => "width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1", :name => "viewport"}
  = display_meta_tags
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags
  = favicon_link_tag 'favicon.ico'
  %script{:src => "http://maps.googleapis.com/maps/api/js?key=AIzaSyAaaNT5i3mCPSCZJZwvYko-gck81Xg3JgE&libraries=places&v=3"}

%body
  = render 'layouts/navbar'
  .container
    .row
      .col-md-8.col-md-offset-2
        - flash.each do |name , msg|
          = content_tag :div , msg , class: "alert alert-info"
    = yield
  %br


%script
  $('.dropdown-toggle').dropdown()
#fb-root
:javascript
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_ES/sdk.js#xfbml=1&version=v2.5";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76050992-1', 'auto');
  ga('send', 'pageview');

:javascript
  !function(d,s,id){
    var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
    if(!d.getElementById(id)){
      js=d.createElement(s);
      js.id=id;
      js.src=p+'://platform.twitter.com/widgets.js';
      fjs.parentNode.insertBefore(js,fjs);
    }
  }(document, 'script', 'twitter-wjs');